/*************** AUTO GENERATED BY REMOTE CONTROL MODULE ***************/

var config =
{
  ipWhitelist: [
    '127.0.0.1',
    '::ffff:127.0.0.1',
    '::1'
  ],
  modules: [
    {
      module: 'alert',
      config: {},
      hidden: false
    },
    {
      module: 'updatenotification',
      position: 'top_bar',
      config: {
        ignoreModules: []
      },
      hidden: false
    },
    {
      module: 'clock',
      position: 'top_left',
      config: {},
      hidden: false
    },
    {
      module: 'calendar',
      header: 'US Holidays',
      position: 'top_left',
      config: {
        calendars: [
          {
            symbol: 'calendar-check',
            url: 'webcal://www.calendarlabs.com/ical-calendar/ics/76/US_Holidays.ics'
          }
        ],
        titleReplace: {
          'De verjaardag van ': '',
          "'s birthday": ''
        },
        locationTitleReplace: {
          'street ': ''
        },
        excludedEvents: []
      },
      hidden: true
    },
    {
      module: 'compliments',
      position: 'lower_third',
      config: {
        compliments: {
          anytime: [
            'Hey there sexy!'
          ],
          morning: [
            'Good morning, handsome!',
            'Enjoy your day!',
            'How was your sleep?'
          ],
          afternoon: [
            'Hello, beauty!',
            'You look sexy!',
            'Looking good today!'
          ],
          evening: [
            'Wow, you look hot!',
            'You look nice!',
            'Hi, sexy!'
          ],
          '....-01-01': [
            'Happy new year!'
          ]
        }
      },
      hidden: false
    },
    {
      module: 'currentweather',
      position: 'top_right',
      config: {
        location: 'New York',
        locationID: '',
        appid: '',
        iconTable: {
          '01d': 'wi-day-sunny',
          '02d': 'wi-day-cloudy',
          '03d': 'wi-cloudy',
          '04d': 'wi-cloudy-windy',
          '09d': 'wi-showers',
          '10d': 'wi-rain',
          '11d': 'wi-thunderstorm',
          '13d': 'wi-snow',
          '50d': 'wi-fog',
          '01n': 'wi-night-clear',
          '02n': 'wi-night-cloudy',
          '03n': 'wi-night-cloudy',
          '04n': 'wi-night-cloudy',
          '09n': 'wi-night-showers',
          '10n': 'wi-night-rain',
          '11n': 'wi-night-thunderstorm',
          '13n': 'wi-night-snow',
          '50n': 'wi-night-alt-cloudy-windy'
        }
      },
      hidden: true
    },
    {
      module: 'weatherforecast',
      position: 'top_right',
      header: 'Weather Forecast',
      config: {
        location: 'New York',
        locationID: '5128581',
        appid: '',
        iconTable: {
          '01d': 'wi-day-sunny',
          '02d': 'wi-day-cloudy',
          '03d': 'wi-cloudy',
          '04d': 'wi-cloudy-windy',
          '09d': 'wi-showers',
          '10d': 'wi-rain',
          '11d': 'wi-thunderstorm',
          '13d': 'wi-snow',
          '50d': 'wi-fog',
          '01n': 'wi-night-clear',
          '02n': 'wi-night-cloudy',
          '03n': 'wi-night-cloudy',
          '04n': 'wi-night-cloudy',
          '09n': 'wi-night-showers',
          '10n': 'wi-night-rain',
          '11n': 'wi-night-thunderstorm',
          '13n': 'wi-night-snow',
          '50n': 'wi-night-alt-cloudy-windy'
        }
      },
      hidden: true
    },
    {
      module: 'newsfeed',
      position: 'bottom_bar',
      config: {
        feeds: [
          {
            title: 'New York Times',
            url: 'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml'
          }
        ],
        startTags: [],
        endTags: [],
        prohibitedWords: []
      },
      hidden: true
    },
    {
      module: 'MMM-Remote-Control',
      config: {
        customCommand: {},
        customMenu: 'custom_menu.json',
        showModuleApiMenu: true,
        apiKey: ''
      },
      hidden: false
    }
  ],
  networkInfo: {
    useHttps: false,
    httpsPrivateKey: '',
    httpsCertificate: '',
    logLevel: [
      'INFO',
      'LOG',
      'WARN',
      'ERROR'
    ]
  }
}

/*************** DO NOT EDIT THE LINE BELOW ***************/
if (typeof module !== 'undefined') {module.exports = config;}
