name: "Close stale issues and PRs"

on:
  workflow_dispatch: # needed for manually running this workflow
  schedule:
    - cron: "30 1 * * 6" # every Saturday at 1:30

permissions:
  issues: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          stale-issue-message: "This issue has been automatically marked as stale because it has not had recent activity. It will be closed if no further activity occurs. Thank you for your contributions."
          days-before-issue-stale: 60
          days-before-issue-close: 7
          operations-per-run: 100
          stale-issue-label: "wontfix"
          exempt-issue-labels: "pinned,security,under investigation,pr welcome,ready (coming with next release)"
